### PR TITLE
Adding Filter on Element

### PR DESCRIPTION
**Pull request by VinceAxe**
Offering a solution to the feature request  #405  opened (by me ...)

### CODE REVIEW

**Comment by Phillipus** [comment]
Thanks. 

Could you break the menu into sub-menus? Like the Model Tree - Business, Application, etc... It's a bit large!

@jbsarrodie Could you look too?

**Comment by jbsarrodie** [comment]
@phillipus Yes I will. BTW Happy Birthday!

@vinceaxe how the hell are you pushing a PR while you're at work ;-)

**Comment by Phillipus** [comment]
> BTW Happy Birthday!

Thanks. So I got a PR for my birthday ;-)

**Comment by jbsarrodie** [comment]
>Thanks. So I got a PR for my birthday ;-)

I can offer you a free copy of a very good ArchiMate modelling tool ;-)

I'll pay you a **bear** the next time we meet !

**Comment by Petrolevb** [comment]
I needed some coffee break, and looked at it during evening anyway

I thought about splitting... But there is quite some complexity due to the
fElementAction that is full fill from another list ... It would have
required to fully split all actions and elementMenu by their layer ... A
lot of duplicated code (I already think about duplicated code between
element and relationship....)

And so Happy Birthday !!!

**Comment by VinceAxe** [comment]
> Could you break the menu into sub-menus? Like the Model Tree - Business, Application, etc... It's a bit large!

Done !

**Comment by Phillipus** [comment]
Cool. Will look at this soon. Question - why are the string like this:

"Element Filter" /* Messages.ZestView_9*/

?

Best to leave them as is and externalise last. :-)

**Comment by Phillipus** [comment]
I'll be taking a look at this next week some time. Leave it with me. :-)

**Comment by Phillipus** [comment]
Thanks for the latest PR. The element list is easier to mange now that we have sub-menus.

However there is a side-effect.

Because the menu items use AS_RADIO_BUTTON style then selecting one will not deselect the current one from another sub-menu. This is because menu items are grouped together in more than one group so exclusive selection does not apply. So either we go back to a huge single sub-menu list or we figure out a hack to deselect the current menu item when selecting a new one.

**Comment by Phillipus** [comment]
I'm working on it...

**Comment by Phillipus** [comment]
Thanks. This pull request has been integrated manually.

**Comment by Phillipus** [comment]
> Thanks. This pull request has been integrated manually.

(That is an automatic message that is generated when I do a PR merge)

Still need to discuss this...

I refactored your code to simplify it, avoiding duplication and a fix for the menu selection issue above.

Could you test the functionality to ensure that the filter works as expected? And also whether it works in combination with the relationship filter?

**Comment by VinceAxe** [comment]
Tested and approved !
Thanks :)

**Pull request closed without merging**
