### PR TITLE
Relationshipfilter

### PR DESCRIPTION
**Pull request by stigbd**
I have been working on a feature to support filtering based on relationship types in the Visualiser, ref #219 

This implementation is working as far as I can see, but some tests are lacking. I do however create this pull request so that you can consider it. Feel free to throw it away. I'd be happy to refactor, and I will also add some more tests later.

### CODE REVIEW

**Comment by Phillipus** [comment]
Thanks for this, I will review it over the next few days. :-)

**Comment by Phillipus** [comment]
Hi, thanks very much for the pull request. I like the idea but I think there are a few changes needed to your code to fit in better with the way the code is structured between model and views.

The problem is that you are adding a filter that is very specific to the visualiser yet much of the code has been added at the model level (all the classes in the model/relationships folder). In fact, some functionality is already provided in other model classes (ArchimateModelUtils). I think that all your code should really belong in the visualiser plugin and much of what you are trying to do can be done with existing code.

Could you take another look at it?

**Comment by stigbd** [comment]
Thank you for reviewing the pull request. I did have a suspicion that there exist classes that can be reused. Thanks for pointing me in the right direction. I will look at it again and try to refactor.

**Comment by Phillipus** [comment]
Please don't let my comments put you off! I realise that it's not so easy for someone else to fit into the "style" of the code. Together we can make it work. :-)

**Comment by stigbd** [comment]
Then I have made a new attempt, this time reusing model-classes. All the classes in the model/relationship folder are gone. I have not been able to extensive testing, so be aware. :-)

**Comment by Phillipus** [comment]
OK, leave it with me...

**Comment by Phillipus** [comment]
I'd like to make some recommendations:

1. Can you simplify the isFiltered() method to:

private boolean isFiltered(IArchimateRelationship rel) {
		if (fRelationship == null){
			return false;
		}	
		return fRelationship != rel.eClass();
	}

2. The last used relationship filter is not being restored when started

3. Can you use names like "Access" instead of "AccessRelationship" in the menu.

4. Some strings ("None") need to be externalised

Thanks!
Phil

**Comment by Phillipus** [comment]
BTW - I like that you have provided a unit test. That's really cool. :-)

**Comment by stigbd** [comment]
Thank you for your helpful comments.
1. I have now simplified the isFiltered() method. I was not happy with the way it was, but I never thought of your elegant solution.
2. Restoring of last used relationship was commented out in my previous version. It is now fixed.
3. To fix the names, I did a simple regexp to use only the part before the second capitalized letter.
4. "None" was externalised by putting it in the messages.properties. I hope that is a straightforward solution.

(There is a small issue with git diff showing some ugly tab/white space/end-of-line diffs, but I'm afraid don't know how to fix it. I'm using Eclipse on linux. Sorry about those.)

Regards,
Stig

**Comment by Phillipus** [comment]
As I needed to make a couple of changes I manually merged this and my changes to a new branch, 'zest_relationship_filter'. I created the branch because (a) I'd like @jbsarrodie to test it, and (b) the help files need updating with text and screenshots which I'll do soonish.

**Comment by Phillipus** [comment]
Forgot to say "thanks" for your contribution, also I know it's not so easy to code against this large code base and try to match the style. :-)

**Comment by jbsarrodie** [comment]
Hi,

I've just tested. It works great and can certainly be useful. My sole comment would be to perhaps rename "none" to "all" (maybe more intuitive).

**Comment by Phillipus** [comment]
Thanks, JB. Changed to "All", as that is what it does. ;-)

**Pull request closed without merging**
