### PR TITLE
Issue 132 LUNA correct git eol character

### PR DESCRIPTION
**Pull request by Andy-Turner**
For this commit I have made no code changes whatsoever.
I used Eclipse Luna and followed the dev setup exactly.
The git repo was a new copy, rebased to archi-HEAD, and
hard reset, and cleaned.

Git was configued for Windows EOL (as specifed that it
should be) and was set to not to automatically change
any line endings.

git config core.eol crlf

git config core.autocrlf false

The repo still has a mix of LF and CRLF.

In this commit I have only done the following in Eclipse:
1. File > Convert Line Delimiters To > Windows
2. Filter Selections > *.java
3. Commit

I have not added anything to will automatically change LF
to CRLF in the future, so people are still free to commit
any line endings they want.

Many of the non-Java files also appear to not have CRLF
EOL

### CODE REVIEW

**Comment by Phillipus** [comment]
Hi Andy. Full marks on your patience! I guess this PR is to demonstrate the issue you're having? Diffs show no chnages in files. I did wonder if it might be an Eclipse refresh issue. There have been times where, in Eclipse, I have seen files that show as being "dirty" and therefore need committing. A "refresh" and "clean" of the projects fixed that. Otherwise try removing all git config files.

**Comment by Phillipus** [comment]
> The repo still has a mix of LF and CRLF.

Can you tell me the files that you see as LF? If so I can take a look at them and fix them up.

**Comment by Andy-Turner** [comment]
Hi. Sorry for the long post, but here is a fresh repo from scratch. I wonder if your GIT client is ignoring EOL chars, so your GIT might think that it matches the remote repo, but since it is ignoring the EOL character it's really not the same as the Github code. The other explanation that I can see is that my PC is random changing the format of files which would be really worrying -- but I guess that could be happening.

> mkdir new_archi_git

> cd new_archi_git

> git clone https://github.com/archimatetool/archi.git
...
Checking out files: 100% (2349/2349), done.

So we now have a completely fresh copy of the repo.

git status
# On branch master
nothing to commit, working directory clean

We can now look at some file as they came from Github:

> cd archi\com.archimatetool.editor\src\com\archimatetool\editor

> gc -TotalCount 2 .\Logger.java
/**
 * This program and the accompanying materials
 
> gc -encoding byte -TotalCount 5 .\Logger.java
47
42
42
13
10

So after "/**" we have chars 13 10 which is CR LF, Windows EOL. We can pick another file in the same dir with the same start:

> gc -TotalCount 2 .\PluginInstaller.java
/**
 * This program and the accompanying materials
 
This file looks identical, so it should also be 13 10 as EOL after "/**":

> gc -encoding byte -TotalCount 5 .\PluginInstaller.java
47
42
42
10
32

Looks like it's only LF, so Linux EOL, there is no character 13 before 10.

We can also see this graphically in Notepad++
image
image

So, with a fresh checkout from Archi GIT we have a mix of CRLF and LF.

Now we can try converting the EOL chars:

image

We can check the EOl char of PluginInstaller.java again:
new_archi_git\archi\com.archimatetool.editor\src\com\archimatetool\editor> gc -encoding byte -TotalCount 5 .\PluginInstaller.java
47
42
42
13
10

Now it has 13 10 which is correct Windows EOL.

image
[git_out.txt](https://github.com/archimatetool/archi/files/136749/git_out.txt)

**Comment by Phillipus** [comment]
I use the in-built git client in Eclipse and also use SmartGit (with default settings). It may be the case that these clients are converting all line endings to CR/LF when checking out but not when committing. What would be the best procedure to check if this is the case?

**Comment by Phillipus** [comment]
I checked out a fresh copy using:

git clone https://github.com/archimatetool/archi.git

I opened PluginInstaller.java in a text editor and showed the line endings. They were CR/LF.

Strange!

**Comment by Phillipus** [comment]
It's probably because I have git for Windows installed like this:

git-setup

**Comment by Phillipus** [comment]
Given that there are indeed many files that have Unix style endings, I wonder what the best course of action is. A mass conversion to CRLF will leave us with many files where looking at diffs becomes a problem. Or we could leave them as is and set the core.autocrlf=true in a .gitattributes file at the top level (alongside the README.MD file).

**Comment by Andy-Turner** [comment]
I think when using core.autocrlf=true, submitting the current CRLF files will result in the entire file being highlighted as being changed as git will commit the CRLF->LF conversion at the same time. I currently have core.autocrlf=false as that was the only way I could find to make edits to a mix of CRLF and LF files in the same commit. As per the link I posted before, the best practice is to use LF for all files and use core.autocrlf=true for Windows; but the repo will still contain a mix of line ending unless a mass convert is done. If you want to continue using a mixture of different EOL then setting core.autocrlf=false should hopefully work on my end.

https://help.github.com/articles/dealing-with-line-endings/

**Comment by Phillipus** [comment]
Depends on "best practice". Eclipse on Windows defaults to CR/LF, and 90% of the development was done on a Windows machine with that set, and git for windows setting. To do a mass convert would be really bad for looking at diffs in files.

**Comment by Phillipus** [comment]
Closing this as we'd need a new PR.

**Pull request closed without merging**
