### PR TITLE
A small fix to put the full screen on the current monitor

### LINKED ISSUE #229: [Bug] Full screen does not respect the monitor choice
Archi 4: 201705031219

When selecting "View" -> "Full Screen", or by pressing F11, the primary display is used instead of the display Archi is on.

Could we do anything about that please? Don't want to have to change primary display whenever using multiple monitors to get full screen on the right display.

### PR DESCRIPTION
**Pull request by stigbd**
Fixes #229

### CODE REVIEW

**Comment by stigbd** [comment]
As I have no access to Windows or MacOs computers, please test this on those platforms. I have tested on Linux 4.10.0-21-generic x86_64 (Ubuntu 17.04 64-bit)

**Comment by Phillipus** [comment]
Thanks. One last thing.

```
int x = bounds.x + (bounds.width - rect.width) / 2;
int y = bounds.y + (bounds.height - rect.height) / 2;
```

This centres the x,y. Could it be even as simple as this one line?

```
fNewShell.setLocation(fOldParent.getShell().getLocation());
```

**Comment by stigbd** [comment]
Nice. I will create a new PR.

**Comment by stigbd** [comment]
Replaced by #232

**Pull request closed without merging**
