### PR TITLE
Data Object may be realized by Artifact

### PR DESCRIPTION
**Pull request by rayl**
http://pubs.opengroup.org/architecture/archimate3-doc/chap09.html#_Toc451758041

### CODE REVIEW

**Comment by Phillipus** [comment]
Hi,
there are many more changes that need to be made to relationships.xml. I think @jbsarrodie will add some more. So I would suggest waiting for a full change set. Maybe we should open an issue to track them all?

**Comment by rayl** [comment]
works for me.  Should i just add comments to that issue then with any items i think need attention?

**Comment by jbsarrodie** [comment]
Hi,

Phil has been quicker than me :-)

Yes, all issues with relationships will be solved later in one shot. The main reason is that the official/normative reference are not the metamodel extracts but the big table on Appendix B. So we are here facing an issue with the standard itself. I'm working inside the ArchiMate forum and so am (with other) collecting all these issues. This should lead to an ArchiMate 3.1 version, but we might imagine publishing a new (bug free) trelationship table in advance for ArchiMate 3.0. If such table is published, it will then be integrated into Archi.

BTW such issues also exist in ArchiMate 2.1: for example a Node assigned to an Infrastructure Function A that has a Flow relationship to another Infrastructure Function B should be lead to (derivation rules for dynamic relationships) a Node that has a Flow relationship to Infrastructure Function B, but this is not allowed in the relationship table....

Regards

**Comment by jbsarrodie** [comment]
I suggest we add new issues to this [GitHub issue](https://github.com/archimatetool/archi/issues/164). I'm doing it now for this one.

**Comment by jbsarrodie** [comment]
If you're ok, I suggest to close this PR...

**Comment by Phillipus** [comment]
Closing. But thanks for contributing it!

**Comment by rayl** [comment]
cool thanks guys.  any idea how long it might take before a new preliminary table is ready for review?

**Comment by jbsarrodie** [comment]
The reporting of issues ends in december, so we should have something (at least internally) in january or february. If for any reasons we can't officially publish an updated table for ArchiMate 3.0, then I'll provide an alternative relationships.xml in january. We'll then have to decide if we include it by default in Archi (but this will not be the real standard and some could argue that at this point Archi is no more ArchiMate compatible) or if we provide it as a file to download manually at your own risk...

**Comment by herve91** [comment]
Hi guys,

Would it be possible to choose between the two on a "pre model" basis ? The choice may be stored in one "metadata" property and kept in the .archimate files.

Regards

**Comment by jbsarrodie** [comment]
Hi Herve,

I don't think this makes sens. IMHO this is clearly a standard issue and as it is now it is unusable, so the ArchiMate forum should update it (and Archi should use the updated version). This can also be a kind of common agreement accross tools vendors.

**Comment by Phillipus** [comment]
I would like to keep things as simple as possible :-)

**Comment by herve91** [comment]
fair enough :-)

**Pull request closed without merging**
