### PR TITLE
[Feature Request] / [Bug] : Improve Link to Editor Function with view

### PR DESCRIPTION
**Pull request by VinceAxe**
Currently the Link to Editor is working quite fine with all archimate concept.
There is an enhancement : if you click inside your view, the link will select the very same view in the model tree.

However, I needed a bit more, which I share here :
When you add Views inside a Diagram (for instance for a 'Welcome' View), you don't have any sync. between the Model and the View inside your diagram.
This is the meaning of this Pull Request
view

### CODE REVIEW

**Comment by VinceAxe** [comment]
To follow the #477

**Comment by Phillipus** [comment]
Thanks! Will get back to this when I have had a think about the best API to combine two things into one thing!

**Comment by Phillipus** [comment]
This turned out to be more complicated than it seems.

- I firstly had to fix an issue with selecting objects asynchronously (see 099c7bc451c489e28a7df4a28aa2eaa1f9d85c61).
- I deprecated IArchimateDiagramEditor#selectArchimateConcepts()
- I refactored ArchimateDiagramEditor#selectObjects() so it can handle any type of object
- I changed TreeSelectionSynchroniser to handle this use case

I've created a branch, "selection-sync" with these changes if you'd like to test this.

**Comment by VinceAxe** [comment]
Seems good for me 
I notice a good point in the new behavior (not sure it was before) : when many diagrams are opened, the selection is made in all diagrams, not only the active one

**Comment by Phillipus** [comment]
It might be easier if I just merge the "selection-sync" branch into master?

**Comment by Phillipus** [comment]
Would it be best if I just merge the "selection-sync" branch into master branch and we can close this? I know it's nice to accept PRs but in this case I had to make several more changes in order to implement this.

**Comment by Phillipus** [comment]
I've added some more changes to support this feature as it wasn't working with Canvas and Sketch Views. So, I'll close this one.

**Pull request closed without merging**
