### PR TITLE
Change element type

### PR DESCRIPTION
**Pull request by etienne-sf**
Hello,

This is a Pull Request, as discussed in Issue #694 ([Feature Request] Change element type).

This issue has been closed a being covered by #663, but it is not, as this last one is about relationship, whereas the #694 is about element type.
I may not reopen it.

In this PR:
* A "Refactor" menu is added into the diagram context menu, and in the Tree View menu. They have been developped based on the other existing actions/commands. In particular, based on the Delete action of the Tree View menu.
* This "Refactor" menu contains submenu, one per element type (Business, Application...). Each of these submenus contain the items of this type.
* The Undo and Redo works for both
* There is no control on the existing relationship for this element. As a consequence, and to be fully operationnal, the #663 issue should be also implemented. This would allow to change relationship's type, when a relationship becomes "illegal" based on the new element type.
    * I can work on the #663 implementation. But I'll start that only if you think you'll accept these two PR.
* The job is done by creating an ArchimateElement of the good type, copying into it the id, name, description and properties from the source one. The replacing the element in all _DiagramModelArchimateObject_ that contain the old one. The new element is created in the same folder (if the element is of the same type), or in the root of the folder's type otherwise
    * A JUnit test checks that the old instance doesn't exist any more in the model
* A tricky and sensitive part is the ability to create an instance of an element type, based on its name, by using Java reflection. It's not very difficult, but it will fail if a name is changed. So a JUnit test checks that instance creation works for every element type.
* It's of course possible to change the type for several elements in the same operation (multiple selections)
* JUnit tests have been added and integrated in the existing test suites. They check the execute, undo and redo actions. And I confirm the good integration in the whole maven build, as I checked that with a failing test.
* The last commit from the archi master has been merged

NB:
* Thanks to your documentation (very clear), I was able to implement and execute JUnit tests, and embed them in the whole build. I check this, as a change in my code has made the JUnit test to fail. And I was happy to double-check it, before raising an issue on them, as this issue was mine ;)
* I also was able to build a Product, and I use it now for my own Archimate work.

Etienne

### CODE REVIEW

**Comment by Phillipus** [comment]
This is along the right track for an implementation, congratulations! :-)

But I'm not going to merge this one because it's not a _draft_ PR (draft PR allows for discussion and changed) and the commits should really be squashed into one commit, or two or three at most. And I think that if you could make it even better.

You have clearly put a lot of work into this and show an understanding of the structure of the code, my only quibbles are in the implementation of the Command and Actions.

- I like that you've used the same folder if the new type is in the same layer
- No need to use reflection to create a new element, simply use `IArchimateFactory.eINSTANCE.create(eclass)`
- I don't want your `.gitignore` file :-)
- Not sure about storing colours for a diagram object. If the colour is default it will change to the default color, if it's been set by the user they might want to keep the same color
- "Features" also need to be copied from elements and diagram objects - I didn't do this either in the jArchi code but it would be easier to do here

You've done a great job here, but as the code could be improved even more my suggestions are:

- Close this PR
- Squash the commits in the branch
- Re-submit as a _draft_ PR (easier to make changes and discuss)
- I can review and make suggestions for improvements
- We can consider merging the final result when we are both happy

**Comment by Phillipus** [comment]
Also, it makes it easier if use a branch rather than `master`

**Comment by Phillipus** [comment]
Draft PRs - https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by Phillipus** [comment]
Another thing - we are about to start work on adding icons to ArchiMate objects together with stereotypes (see https://github.com/archimatetool/archi/projects/6). This will likely affect changing the element type. So this may in fact take longer to implement in the long run.

**Comment by etienne-sf** [comment]
Hello,

Thanks for your quick comment. 

I'll publish a draft PR, with your comments taken into account . 

What about the icon stuff : do you already have an idea on the impact?
Or we will see when this happen?

Étienne

**Comment by Phillipus** [comment]
> What about the icon stuff: do you already have an idea on the impact?

A DMO (Diagram Model Object) will also have a path to an image and image position information. But it will be best to use `ECoreUtil#copy` methods to clone objects. I will discuss more in the draft PR.

**Comment by etienne-sf** [comment]
Closing as requested. I'll create a Daft PR instead

**Comment by etienne-sf** [comment]
Apparently, I can't create a "Draft PR".

AFAI, from the https://github.blog/2019-02-14-introducing-draft-pull-requests/ page (and others github docs), I should have this menu in the "Create Pull Request" green button.
But I don't have it.

From the https://github.community/t/draft-pull-requests-are-not-available-on-our-private-repositories-in-last-few-days/2466 page, understand that Draft PR was widely available, but is now less available. Only for repositories that respect this:

_Draft pull requests are available in public repositories with GitHub Free for organizations and legacy per-repository billing plans, and in public and private repositories with GitHub Team, GitHub Enterprise Server 2.17+, and GitHub Enterprise Cloud_

Etienne

**Comment by Phillipus** [comment]
That's strange. We used to be able to create draft PRs. It seems that I can't create draft PRs for the `archimatetool` organisation nor on my own personal `Phillipus` public repositories. So I'm not really clear who can create draft PRs.

**Comment by Phillipus** [comment]
"Draft pull requests are available in public repositories with GitHub Free for organizations"

As far as I can see the `archimatetool` organization is a "GitHub Free" one. @jbsarrodie What do you think? Draft PRs were available before now.

**Comment by Phillipus** [comment]
@etienne-sf You can create draft PRs. It's in the drop down after you press the first button:

Screenshot 2020-12-30 at 18 20 20

**Comment by Phillipus** [comment]
This is in Archi 5.1 beta.

**Pull request closed without merging**
